[build]
  publish = "static"
  command = "echo 'Frontend build complete'"

[[redirects]]
  from = "/api/*"
  to = "https://BACKEND_URL/api/:splat"  # Replace with your actual backend URL when you have it
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cargo run"
  port = 8888
  targetPort = 3000
  framework = "#static"