[phases.setup]
nixPkgs = ['rust', 'cargo', 'pkg-config', 'openssl', 'gcc', 'libc6-dev']

[phases.build]
cmds = [
  'cargo build --release',
  'ls -la target/release/'
]

[phases.start]
cmd = './target/release/cybersecurity-research-app'

[variables]
RUST_LOG = 'info'
PORT = '3000'