[phases.setup]
nixPkgs = ["cargo", "rustc", "pkg-config", "openssl"]

[phases.build]
cmds = ["cargo build --release"]

[phases.start]
cmd = "./target/release/cybersecurity-research-app"

[variables]
RUST_LOG = "info"
PORT = "3000"