[phases.setup]
nixPkgs = ['rust', 'cargo', 'pkg-config', 'openssl']

[phases.build]
cmds = ['cargo build --release']

[phases.start]
cmd = 'cargo run --release'

[variables]
RUST_LOG = 'info'
PORT = '3000'